### ISSUE TITLE
"merge-with-parent" fails when a merge would succeed as non-fast-forward

### ISSUE THREAD

**Issue by akx** [CircleCI-Public/build-tools-orb#29]
### Orb version

2.7.0

### What happened

A merge-with-parent step fails because it's doing a real merge, but doesn't have an identity for the non-fast-forward merge commit. (A fast-forward merge wouldn't require a new commit object, so it needs no identity either.)

```
#!/bin/bash --login
CHILD_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$CHILD_BRANCH" = "master" ]; then
  echo "Can't merge branch into itself! Skipping."
  exit 0
fi
git checkout master
git merge $CHILD_BRANCH
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'circleci@redactedmachineid.(none)')
```

### Expected behavior

The merge should succeed without manual configuration. Maybe the implementation should set the [environment variables](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables)

* `GIT_AUTHOR_NAME`: the human-readable name in the “author” field.
* `GIT_AUTHOR_EMAIL`: the email for the “author” field.

implicitly?

**Comment by gmemstr** [comment]
Being fixed in #28
