### ISSUE TITLE
"merge-with-parent" on 2.8.0 still fails

### ISSUE THREAD

**Issue by akx** [CircleCI-Public/build-tools-orb#31]
### Orb version

2.8.0

### What happened

Refs #29 – 2.8.0 fixed the non-existing user but Git would also like to have a merge message without opening up an editor for it.
```
#!/bin/bash --login
CHILD_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$CHILD_BRANCH" = "master" ]; then
  echo "Can't merge branch into itself! Skipping."
  exit 0
fi
git checkout master
git merge $CHILD_BRANCH
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
error: Terminal is dumb, but EDITOR unset
Not committing merge; use 'git commit' to complete the merge.

Exited with code exit status 1
CircleCI received exit code 1
```

### Expected behavior

The merge should succeed with some default message.

**Comment by gmemstr** [comment]
Interesting - according to the [integration tests](https://app.circleci.com/pipelines/github/CircleCI-Public/build-tools-orb/564/workflows/99ed2577-a698-45aa-8a2c-5f9f8e9eaf95/jobs/1513), this goes off without a hitch, so I wonder what might require the editor (I can't recall the exact scenario off the top of my head).
