### ISSUE TITLE
Bash/envar orb

### ISSUE THREAD

**Issue by iynere** [CircleCI-Public/build-tools-orb#8]
Requested by Pantheon during tech meeting. Will be very valuable to many everyday customers as well. Will fix one of the common gotchas with CircleCI and setting/passing envars.

**Comment by glenjamin** [comment]
something along the lines of
```
add_env_var:
  name: VAR
  value: somebash
```

that takes care of escaping correctly when appending to $BASH_ENV

**Comment by glenjamin** [comment]
Me and Alex worked on this during a donut pair, and he’s since refined it a bit:

https://github.com/CircleCI-Public/rememborb

**Comment by dsayling** [comment]
Use https://github.com/CircleCI-Public/rememborb
